branch-defaults:
  master:
    environment: mediaff-admin
environment-defaults:
  mediaff-admin:
    branch: master
    repository: mediaff.com
global:
  application_name: mediaff.com
  branch: master
  default_ec2_keyname: mediaff
  default_platform: PHP 7.0
  default_region: us-east-1
  profile: eb-cli
  repository: mediaff.com
  sc: git
