<?php

namespace AppBundle\Repository;

/**
 * PartnerDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
