<?php

namespace AppBundle\Repository;

/**
 * StatsDailyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsDailyRepository extends \Doctrine\ORM\EntityRepository
{
}
