<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Campaigns extends \AppBundle\Entity\Campaigns implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'userid', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'app', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'fromName', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'fromEmail', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'replyTo', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'label', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'plainText', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'htmlText', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'queryString', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'sent', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'toSend', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'toSendLists', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'recipients', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'timeoutCheck', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'opens', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'wysiwyg', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'sendDate', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'lists', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'timezone', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'errors', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'bounceSetup', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'complaintSetup', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'openstacking', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'linkstracking'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'userid', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'app', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'fromName', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'fromEmail', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'replyTo', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'label', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'plainText', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'htmlText', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'queryString', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'sent', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'toSend', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'toSendLists', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'recipients', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'timeoutCheck', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'opens', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'wysiwyg', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'sendDate', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'lists', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'timezone', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'errors', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'bounceSetup', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'complaintSetup', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'openstacking', '' . "\0" . 'AppBundle\\Entity\\Campaigns' . "\0" . 'linkstracking'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Campaigns $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserid($userid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserid', [$userid]);

        return parent::setUserid($userid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserid', []);

        return parent::getUserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setApp($app)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApp', [$app]);

        return parent::setApp($app);
    }

    /**
     * {@inheritDoc}
     */
    public function getApp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApp', []);

        return parent::getApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromName($fromName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromName', [$fromName]);

        return parent::setFromName($fromName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromName', []);

        return parent::getFromName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromEmail($fromEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromEmail', [$fromEmail]);

        return parent::setFromEmail($fromEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromEmail', []);

        return parent::getFromEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setReplyTo($replyTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReplyTo', [$replyTo]);

        return parent::setReplyTo($replyTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getReplyTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReplyTo', []);

        return parent::getReplyTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainText($plainText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainText', [$plainText]);

        return parent::setPlainText($plainText);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainText', []);

        return parent::getPlainText();
    }

    /**
     * {@inheritDoc}
     */
    public function setHtmlText($htmlText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHtmlText', [$htmlText]);

        return parent::setHtmlText($htmlText);
    }

    /**
     * {@inheritDoc}
     */
    public function getHtmlText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHtmlText', []);

        return parent::getHtmlText();
    }

    /**
     * {@inheritDoc}
     */
    public function setQueryString($queryString)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQueryString', [$queryString]);

        return parent::setQueryString($queryString);
    }

    /**
     * {@inheritDoc}
     */
    public function getQueryString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQueryString', []);

        return parent::getQueryString();
    }

    /**
     * {@inheritDoc}
     */
    public function setSent($sent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSent', [$sent]);

        return parent::setSent($sent);
    }

    /**
     * {@inheritDoc}
     */
    public function getSent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSent', []);

        return parent::getSent();
    }

    /**
     * {@inheritDoc}
     */
    public function setToSend($toSend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToSend', [$toSend]);

        return parent::setToSend($toSend);
    }

    /**
     * {@inheritDoc}
     */
    public function getToSend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToSend', []);

        return parent::getToSend();
    }

    /**
     * {@inheritDoc}
     */
    public function setToSendLists($toSendLists)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToSendLists', [$toSendLists]);

        return parent::setToSendLists($toSendLists);
    }

    /**
     * {@inheritDoc}
     */
    public function getToSendLists()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToSendLists', []);

        return parent::getToSendLists();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecipients($recipients)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecipients', [$recipients]);

        return parent::setRecipients($recipients);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipients()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipients', []);

        return parent::getRecipients();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeoutCheck($timeoutCheck)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeoutCheck', [$timeoutCheck]);

        return parent::setTimeoutCheck($timeoutCheck);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeoutCheck()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeoutCheck', []);

        return parent::getTimeoutCheck();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpens($opens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpens', [$opens]);

        return parent::setOpens($opens);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpens', []);

        return parent::getOpens();
    }

    /**
     * {@inheritDoc}
     */
    public function setWysiwyg($wysiwyg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWysiwyg', [$wysiwyg]);

        return parent::setWysiwyg($wysiwyg);
    }

    /**
     * {@inheritDoc}
     */
    public function getWysiwyg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWysiwyg', []);

        return parent::getWysiwyg();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendDate($sendDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendDate', [$sendDate]);

        return parent::setSendDate($sendDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendDate', []);

        return parent::getSendDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLists($lists)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLists', [$lists]);

        return parent::setLists($lists);
    }

    /**
     * {@inheritDoc}
     */
    public function getLists()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLists', []);

        return parent::getLists();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimezone($timezone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimezone', [$timezone]);

        return parent::setTimezone($timezone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimezone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimezone', []);

        return parent::getTimezone();
    }

    /**
     * {@inheritDoc}
     */
    public function setErrors($errors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setErrors', [$errors]);

        return parent::setErrors($errors);
    }

    /**
     * {@inheritDoc}
     */
    public function getErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErrors', []);

        return parent::getErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function setBounceSetup($bounceSetup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBounceSetup', [$bounceSetup]);

        return parent::setBounceSetup($bounceSetup);
    }

    /**
     * {@inheritDoc}
     */
    public function getBounceSetup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBounceSetup', []);

        return parent::getBounceSetup();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplaintSetup($complaintSetup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplaintSetup', [$complaintSetup]);

        return parent::setComplaintSetup($complaintSetup);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplaintSetup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplaintSetup', []);

        return parent::getComplaintSetup();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenstacking($openstacking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenstacking', [$openstacking]);

        return parent::setOpenstacking($openstacking);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpenstacking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpenstacking', []);

        return parent::getOpenstacking();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkstracking($linkstracking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkstracking', [$linkstracking]);

        return parent::setLinkstracking($linkstracking);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkstracking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkstracking', []);

        return parent::getLinkstracking();
    }

}
