<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SubscriberADKCampaign extends \AppBundle\Entity\SubscriberADKCampaign implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'requestid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'mailingid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'mailingtypeid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'scheduleeventtypeid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'scheduledate', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'recipient', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'list', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'cid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'campaignrank', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'categoryid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'templateid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'from_field', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'friendlyfrom', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'subjectid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'subject', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'creativeid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'body', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'clickurl', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'textbody', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'finalemail', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'htmlcreativelength', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'textcreativelength', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'datecreated', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'batchnum'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'requestid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'mailingid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'mailingtypeid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'scheduleeventtypeid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'scheduledate', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'recipient', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'list', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'cid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'campaignrank', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'categoryid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'templateid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'from_field', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'friendlyfrom', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'subjectid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'subject', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'creativeid', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'body', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'clickurl', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'textbody', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'finalemail', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'htmlcreativelength', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'textcreativelength', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'datecreated', '' . "\0" . 'AppBundle\\Entity\\SubscriberADKCampaign' . "\0" . 'batchnum'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SubscriberADKCampaign $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequestid($requestid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequestid', [$requestid]);

        return parent::setRequestid($requestid);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestid', []);

        return parent::getRequestid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailingid($mailingid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailingid', [$mailingid]);

        return parent::setMailingid($mailingid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailingid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailingid', []);

        return parent::getMailingid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailingtypeid($mailingtypeid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailingtypeid', [$mailingtypeid]);

        return parent::setMailingtypeid($mailingtypeid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailingtypeid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailingtypeid', []);

        return parent::getMailingtypeid();
    }

    /**
     * {@inheritDoc}
     */
    public function setScheduleeventtypeid($scheduleeventtypeid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScheduleeventtypeid', [$scheduleeventtypeid]);

        return parent::setScheduleeventtypeid($scheduleeventtypeid);
    }

    /**
     * {@inheritDoc}
     */
    public function getScheduleeventtypeid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScheduleeventtypeid', []);

        return parent::getScheduleeventtypeid();
    }

    /**
     * {@inheritDoc}
     */
    public function setScheduledate($scheduledate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScheduledate', [$scheduledate]);

        return parent::setScheduledate($scheduledate);
    }

    /**
     * {@inheritDoc}
     */
    public function getScheduledate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScheduledate', []);

        return parent::getScheduledate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecipient($recipient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecipient', [$recipient]);

        return parent::setRecipient($recipient);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipient', []);

        return parent::getRecipient();
    }

    /**
     * {@inheritDoc}
     */
    public function setList($list)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setList', [$list]);

        return parent::setList($list);
    }

    /**
     * {@inheritDoc}
     */
    public function getList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getList', []);

        return parent::getList();
    }

    /**
     * {@inheritDoc}
     */
    public function setCid($cid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCid', [$cid]);

        return parent::setCid($cid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCid', []);

        return parent::getCid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCampaignrank($campaignrank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCampaignrank', [$campaignrank]);

        return parent::setCampaignrank($campaignrank);
    }

    /**
     * {@inheritDoc}
     */
    public function getCampaignrank()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampaignrank', []);

        return parent::getCampaignrank();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryid($categoryid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryid', [$categoryid]);

        return parent::setCategoryid($categoryid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryid', []);

        return parent::getCategoryid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemplateid($templateid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemplateid', [$templateid]);

        return parent::setTemplateid($templateid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemplateid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemplateid', []);

        return parent::getTemplateid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromField($fromField)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromField', [$fromField]);

        return parent::setFromField($fromField);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromField()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromField', []);

        return parent::getFromField();
    }

    /**
     * {@inheritDoc}
     */
    public function setFriendlyfrom($friendlyfrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFriendlyfrom', [$friendlyfrom]);

        return parent::setFriendlyfrom($friendlyfrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getFriendlyfrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFriendlyfrom', []);

        return parent::getFriendlyfrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubjectid($subjectid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubjectid', [$subjectid]);

        return parent::setSubjectid($subjectid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubjectid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubjectid', []);

        return parent::getSubjectid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject($subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', [$subject]);

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreativeid($creativeid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreativeid', [$creativeid]);

        return parent::setCreativeid($creativeid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreativeid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreativeid', []);

        return parent::getCreativeid();
    }

    /**
     * {@inheritDoc}
     */
    public function setBody($body)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBody', [$body]);

        return parent::setBody($body);
    }

    /**
     * {@inheritDoc}
     */
    public function getBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBody', []);

        return parent::getBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setClickurl($clickurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClickurl', [$clickurl]);

        return parent::setClickurl($clickurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getClickurl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClickurl', []);

        return parent::getClickurl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextbody($textbody)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextbody', [$textbody]);

        return parent::setTextbody($textbody);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextbody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextbody', []);

        return parent::getTextbody();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinalemail($finalemail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinalemail', [$finalemail]);

        return parent::setFinalemail($finalemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinalemail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinalemail', []);

        return parent::getFinalemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setHtmlcreativelength($htmlcreativelength)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHtmlcreativelength', [$htmlcreativelength]);

        return parent::setHtmlcreativelength($htmlcreativelength);
    }

    /**
     * {@inheritDoc}
     */
    public function getHtmlcreativelength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHtmlcreativelength', []);

        return parent::getHtmlcreativelength();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextcreativelength($textcreativelength)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextcreativelength', [$textcreativelength]);

        return parent::setTextcreativelength($textcreativelength);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextcreativelength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextcreativelength', []);

        return parent::getTextcreativelength();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreated($datecreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreated', [$datecreated]);

        return parent::setDatecreated($datecreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreated', []);

        return parent::getDatecreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setBatchnum($batchnum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBatchnum', [$batchnum]);

        return parent::setBatchnum($batchnum);
    }

    /**
     * {@inheritDoc}
     */
    public function getBatchnum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBatchnum', []);

        return parent::getBatchnum();
    }

}
