<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SubscriberOptInDetails extends \AppBundle\Entity\SubscriberOptInDetails implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'resourceid', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'agreeterms', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'agreeemails', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'agreepartners', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'optindate', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'optinip'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'resourceid', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'agreeterms', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'agreeemails', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'agreepartners', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'optindate', '' . "\0" . 'AppBundle\\Entity\\SubscriberOptInDetails' . "\0" . 'optinip'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SubscriberOptInDetails $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResourceid($resourceid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourceid', [$resourceid]);

        return parent::setResourceid($resourceid);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceid', []);

        return parent::getResourceid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgreeterms($agreeterms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgreeterms', [$agreeterms]);

        return parent::setAgreeterms($agreeterms);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgreeterms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgreeterms', []);

        return parent::getAgreeterms();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgreeemails($agreeemails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgreeemails', [$agreeemails]);

        return parent::setAgreeemails($agreeemails);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgreeemails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgreeemails', []);

        return parent::getAgreeemails();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgreepartners($agreepartners)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgreepartners', [$agreepartners]);

        return parent::setAgreepartners($agreepartners);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgreepartners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgreepartners', []);

        return parent::getAgreepartners();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptindate($optindate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptindate', [$optindate]);

        return parent::setOptindate($optindate);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptindate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptindate', []);

        return parent::getOptindate();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptinip($optinip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptinip', [$optinip]);

        return parent::setOptinip($optinip);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptinip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptinip', []);

        return parent::getOptinip();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\AppBundle\Entity\SubscriberDetails $id = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$id]);

        return parent::setUser($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

}
