<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CampaignInputDetails extends \AppBundle\Entity\CampaignInputDetails implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'partnername', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'resourcename', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'templatename', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'numemails', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'timezone', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'datetosend', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'geo', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'link1', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'link2'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'partnername', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'resourcename', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'templatename', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'numemails', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'timezone', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'datetosend', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'geo', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'link1', '' . "\0" . 'AppBundle\\Entity\\CampaignInputDetails' . "\0" . 'link2'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CampaignInputDetails $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnername($partnername)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnername', [$partnername]);

        return parent::setPartnername($partnername);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnername', []);

        return parent::getPartnername();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumemails($numemails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumemails', [$numemails]);

        return parent::setNumemails($numemails);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumemails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumemails', []);

        return parent::getNumemails();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setResourcename($resourcename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResourcename', [$resourcename]);

        return parent::setResourcename($resourcename);
    }

    /**
     * {@inheritDoc}
     */
    public function getResourcename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourcename', []);

        return parent::getResourcename();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemplatename($templatename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemplatename', [$templatename]);

        return parent::setTemplatename($templatename);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemplatename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemplatename', []);

        return parent::getTemplatename();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimezone($timezone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimezone', [$timezone]);

        return parent::setTimezone($timezone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimezone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimezone', []);

        return parent::getTimezone();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatetosend($datetosend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatetosend', [$datetosend]);

        return parent::setDatetosend($datetosend);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatetosend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatetosend', []);

        return parent::getDatetosend();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeo($geo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeo', [$geo]);

        return parent::setGeo($geo);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeo', []);

        return parent::getGeo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink1($link1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink1', [$link1]);

        return parent::setLink1($link1);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink1', []);

        return parent::getLink1();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink2($link2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink2', [$link2]);

        return parent::setLink2($link2);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink2', []);

        return parent::getLink2();
    }

}
