<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SendyApps extends \AppBundle\Entity\SendyApps implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'userid', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'appName', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'fromName', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'fromEmail', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'replyTo', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'currency', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'deliveryFee', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'costPerRecipient', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'smtpHost', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'smtpPort', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'smtpSsl', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'smtpUsername', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'smtpPassword', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'bounceSetup', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'camplaintSetup', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'appKey', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'allocatedQuota', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'currentQuota', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'dayOfReset', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'monthOfNextReset', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'testEmail', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'brandLogoFilename', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'allowedAttachments', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'reportsOnly'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'userid', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'appName', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'fromName', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'fromEmail', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'replyTo', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'currency', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'deliveryFee', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'costPerRecipient', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'smtpHost', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'smtpPort', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'smtpSsl', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'smtpUsername', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'smtpPassword', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'bounceSetup', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'camplaintSetup', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'appKey', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'allocatedQuota', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'currentQuota', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'dayOfReset', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'monthOfNextReset', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'testEmail', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'brandLogoFilename', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'allowedAttachments', '' . "\0" . 'AppBundle\\Entity\\SendyApps' . "\0" . 'reportsOnly'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SendyApps $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserid($userid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserid', [$userid]);

        return parent::setUserid($userid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserid', []);

        return parent::getUserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppName($appName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppName', [$appName]);

        return parent::setAppName($appName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppName', []);

        return parent::getAppName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromName($fromName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromName', [$fromName]);

        return parent::setFromName($fromName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromName', []);

        return parent::getFromName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromEmail($fromEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromEmail', [$fromEmail]);

        return parent::setFromEmail($fromEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromEmail', []);

        return parent::getFromEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setReplyTo($replyTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReplyTo', [$replyTo]);

        return parent::setReplyTo($replyTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getReplyTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReplyTo', []);

        return parent::getReplyTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryFee($deliveryFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryFee', [$deliveryFee]);

        return parent::setDeliveryFee($deliveryFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryFee', []);

        return parent::getDeliveryFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setCostPerRecipient($costPerRecipient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostPerRecipient', [$costPerRecipient]);

        return parent::setCostPerRecipient($costPerRecipient);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostPerRecipient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostPerRecipient', []);

        return parent::getCostPerRecipient();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpHost($smtpHost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpHost', [$smtpHost]);

        return parent::setSmtpHost($smtpHost);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpHost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpHost', []);

        return parent::getSmtpHost();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpPort($smtpPort)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpPort', [$smtpPort]);

        return parent::setSmtpPort($smtpPort);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpPort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpPort', []);

        return parent::getSmtpPort();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpSsl($smtpSsl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpSsl', [$smtpSsl]);

        return parent::setSmtpSsl($smtpSsl);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpSsl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpSsl', []);

        return parent::getSmtpSsl();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpUsername($smtpUsername)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpUsername', [$smtpUsername]);

        return parent::setSmtpUsername($smtpUsername);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpUsername', []);

        return parent::getSmtpUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmtpPassword($smtpPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmtpPassword', [$smtpPassword]);

        return parent::setSmtpPassword($smtpPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmtpPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmtpPassword', []);

        return parent::getSmtpPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setBounceSetup($bounceSetup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBounceSetup', [$bounceSetup]);

        return parent::setBounceSetup($bounceSetup);
    }

    /**
     * {@inheritDoc}
     */
    public function getBounceSetup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBounceSetup', []);

        return parent::getBounceSetup();
    }

    /**
     * {@inheritDoc}
     */
    public function setCamplaintSetup($complaintSetup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCamplaintSetup', [$complaintSetup]);

        return parent::setCamplaintSetup($complaintSetup);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplaintSetup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplaintSetup', []);

        return parent::getComplaintSetup();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppKey($appKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppKey', [$appKey]);

        return parent::setAppKey($appKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppKey', []);

        return parent::getAppKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllocatedQuota($allocatedQuota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllocatedQuota', [$allocatedQuota]);

        return parent::setAllocatedQuota($allocatedQuota);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllocatedQuota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllocatedQuota', []);

        return parent::getAllocatedQuota();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentQuota($currentQuota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentQuota', [$currentQuota]);

        return parent::setCurrentQuota($currentQuota);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentQuota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentQuota', []);

        return parent::getCurrentQuota();
    }

    /**
     * {@inheritDoc}
     */
    public function setDayOfReset($dayOfReset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDayOfReset', [$dayOfReset]);

        return parent::setDayOfReset($dayOfReset);
    }

    /**
     * {@inheritDoc}
     */
    public function getDayOfReset()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDayOfReset', []);

        return parent::getDayOfReset();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonthOfNextReset($monthOfNextReset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonthOfNextReset', [$monthOfNextReset]);

        return parent::setMonthOfNextReset($monthOfNextReset);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonthOfNextReset()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonthOfNextReset', []);

        return parent::getMonthOfNextReset();
    }

    /**
     * {@inheritDoc}
     */
    public function setTestEmail($testEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTestEmail', [$testEmail]);

        return parent::setTestEmail($testEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getTestEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTestEmail', []);

        return parent::getTestEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrandLogoFilename($brandLogoFilename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrandLogoFilename', [$brandLogoFilename]);

        return parent::setBrandLogoFilename($brandLogoFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrandLogoFilename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrandLogoFilename', []);

        return parent::getBrandLogoFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowedAttachments($allowedAttachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowedAttachments', [$allowedAttachments]);

        return parent::setAllowedAttachments($allowedAttachments);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowedAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowedAttachments', []);

        return parent::getAllowedAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportsOnly($reportsOnly)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportsOnly', [$reportsOnly]);

        return parent::setReportsOnly($reportsOnly);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportsOnly()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportsOnly', []);

        return parent::getReportsOnly();
    }

    /**
     * {@inheritDoc}
     */
    public function getCamplaintSetup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCamplaintSetup', []);

        return parent::getCamplaintSetup();
    }

    /**
     * {@inheritDoc}
     */
    public function addAppdetail(\AppBundle\Entity\Template $appdetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAppdetail', [$appdetail]);

        return parent::addAppdetail($appdetail);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAppdetail(\AppBundle\Entity\Template $appdetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAppdetail', [$appdetail]);

        return parent::removeAppdetail($appdetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppdetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppdetails', []);

        return parent::getAppdetails();
    }

}
