<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lists extends \AppBundle\Entity\Lists implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'app', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'userid', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'opt_in', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'confirm_url', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'subscribed_url', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'unsubscribed_url', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'thankyou', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'thankyou_subject', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'thankyou_message', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'goodbye', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'goodbye_subject', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'goodbye_message', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'confirmation_subject', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'confirmation_email', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'unsubscribe_all_list', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'custom_fields', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'prev_count', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'currently_processing', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'total_records'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'app', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'userid', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'opt_in', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'confirm_url', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'subscribed_url', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'unsubscribed_url', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'thankyou', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'thankyou_subject', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'thankyou_message', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'goodbye', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'goodbye_subject', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'goodbye_message', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'confirmation_subject', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'confirmation_email', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'unsubscribe_all_list', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'custom_fields', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'prev_count', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'currently_processing', '' . "\0" . 'AppBundle\\Entity\\Lists' . "\0" . 'total_records'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lists $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setApp($app)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApp', [$app]);

        return parent::setApp($app);
    }

    /**
     * {@inheritDoc}
     */
    public function getApp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApp', []);

        return parent::getApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserid($userid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserid', [$userid]);

        return parent::setUserid($userid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserid', []);

        return parent::getUserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptIn($optIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptIn', [$optIn]);

        return parent::setOptIn($optIn);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptIn', []);

        return parent::getOptIn();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmUrl($confirmUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmUrl', [$confirmUrl]);

        return parent::setConfirmUrl($confirmUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmUrl', []);

        return parent::getConfirmUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubscribedUrl($subscribedUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubscribedUrl', [$subscribedUrl]);

        return parent::setSubscribedUrl($subscribedUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubscribedUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubscribedUrl', []);

        return parent::getSubscribedUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnsubscribedUrl($unsubscribedUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnsubscribedUrl', [$unsubscribedUrl]);

        return parent::setUnsubscribedUrl($unsubscribedUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnsubscribedUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnsubscribedUrl', []);

        return parent::getUnsubscribedUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setThankyou($thankyou)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThankyou', [$thankyou]);

        return parent::setThankyou($thankyou);
    }

    /**
     * {@inheritDoc}
     */
    public function getThankyou()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThankyou', []);

        return parent::getThankyou();
    }

    /**
     * {@inheritDoc}
     */
    public function setThankyouSubject($thankyouSubject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThankyouSubject', [$thankyouSubject]);

        return parent::setThankyouSubject($thankyouSubject);
    }

    /**
     * {@inheritDoc}
     */
    public function getThankyouSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThankyouSubject', []);

        return parent::getThankyouSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setThankyouMessage($thankyouMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThankyouMessage', [$thankyouMessage]);

        return parent::setThankyouMessage($thankyouMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getThankyouMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThankyouMessage', []);

        return parent::getThankyouMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoodbye($goodbye)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoodbye', [$goodbye]);

        return parent::setGoodbye($goodbye);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoodbye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoodbye', []);

        return parent::getGoodbye();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoodbyeSubject($goodbyeSubject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoodbyeSubject', [$goodbyeSubject]);

        return parent::setGoodbyeSubject($goodbyeSubject);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoodbyeSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoodbyeSubject', []);

        return parent::getGoodbyeSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoodbyeMessage($goodbyeMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoodbyeMessage', [$goodbyeMessage]);

        return parent::setGoodbyeMessage($goodbyeMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoodbyeMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoodbyeMessage', []);

        return parent::getGoodbyeMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationSubject($confirmationSubject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationSubject', [$confirmationSubject]);

        return parent::setConfirmationSubject($confirmationSubject);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationSubject', []);

        return parent::getConfirmationSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationEmail($confirmationEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationEmail', [$confirmationEmail]);

        return parent::setConfirmationEmail($confirmationEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationEmail', []);

        return parent::getConfirmationEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnsubscribeAllList($unsubscribeAllList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnsubscribeAllList', [$unsubscribeAllList]);

        return parent::setUnsubscribeAllList($unsubscribeAllList);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnsubscribeAllList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnsubscribeAllList', []);

        return parent::getUnsubscribeAllList();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomFields($customFields)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomFields', [$customFields]);

        return parent::setCustomFields($customFields);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomFields', []);

        return parent::getCustomFields();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrevCount($prevCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrevCount', [$prevCount]);

        return parent::setPrevCount($prevCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrevCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrevCount', []);

        return parent::getPrevCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentlyProcessing($currentlyProcessing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentlyProcessing', [$currentlyProcessing]);

        return parent::setCurrentlyProcessing($currentlyProcessing);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentlyProcessing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentlyProcessing', []);

        return parent::getCurrentlyProcessing();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalRecords($totalRecords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalRecords', [$totalRecords]);

        return parent::setTotalRecords($totalRecords);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalRecords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalRecords', []);

        return parent::getTotalRecords();
    }

}
